# Generated by Django 3.2.5 on 2021-07-05 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='type_delivery',
            field=models.CharField(choices=[('SELF', 'Самовивоз'), ('DELIVERY', 'Доставка')], max_length=255, verbose_name='Тип доставки'),
        ),
    ]
