# Generated by Django 3.2.5 on 2021-07-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_type_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='type_delivery',
            field=models.CharField(max_length=255, verbose_name='Тип доставки'),
        ),
    ]
