# Generated by Django 3.2.5 on 2021-07-26 11:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_type_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 26, 11, 23, 39, 271991, tzinfo=utc), verbose_name='Дата на виконання'),
        ),
    ]
