# Generated by Django 3.2.5 on 2021-07-26 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_date',
        ),
    ]
