# Generated by Django 3.2.5 on 2021-07-26 11:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_remove_order_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 26, 11, 42, 47, 535696, tzinfo=utc), verbose_name='Дата на виконання'),
        ),
    ]
