# Generated by Django 3.2.5 on 2021-09-08 17:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_alter_order_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2021, 9, 8, 17, 25, 40, 617757, tzinfo=utc), verbose_name='Дата на виконання'),
        ),
    ]
