# Generated by Django 3.2.5 on 2021-10-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_alter_order_order_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Назва промокода')),
                ('interest', models.PositiveIntegerField(verbose_name='Відсотки промокода')),
                ('start_of_action', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
