# Generated by Django 3.2.5 on 2021-10-12 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_promocode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promocode',
            options={'verbose_name': 'Промо код', 'verbose_name_plural': 'Промо коди'},
        ),
        migrations.AlterField(
            model_name='promocode',
            name='start_of_action',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
