# Generated by Django 3.2.5 on 2021-10-12 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_auto_20211012_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promocode',
            old_name='start_of_action',
            new_name='end_of_action',
        ),
    ]
