# Generated by Django 3.2.5 on 2021-10-12 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0023_rename_start_of_action_promocode_end_of_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='name',
            field=models.CharField(max_length=32, null=True, verbose_name='Назва промокода'),
        ),
    ]
