# Generated by Django 3.2.5 on 2021-10-12 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0024_alter_promocode_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price_with_promo_code',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Сума замовлення із можливим промокодом'),
        ),
        migrations.AddField(
            model_name='order',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.promocode', verbose_name='Промокод замовлення'),
        ),
    ]
