# Generated by Django 3.2.5 on 2021-11-06 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0027_order_promo_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='end_of_action',
            field=models.DateTimeField(),
        ),
    ]
