# Generated by Django 3.2.5 on 2021-07-14 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproduct',
            name='user',
        ),
    ]
