# Generated by Django 3.2.5 on 2021-07-16 11:01

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_cartproduct_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=autoslug.fields.AutoSlugField(allow_unicode=True, editable=True, max_length=255, populate_from='title', unique=True),
        ),
    ]
