# Generated by Django 3.2.5 on 2021-07-18 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20210716_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='shop.category', verbose_name='Категорії'),
        ),
        migrations.AlterField(
            model_name='shortimgproduct',
            name='img',
            field=models.URLField(verbose_name='Фото'),
        ),
    ]
