# Generated by Django 3.2.5 on 2021-07-20 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_cartproduct_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='product',
            new_name='product1',
        ),
    ]
