# Generated by Django 3.2.5 on 2021-07-20 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_rename_product_review_product1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='product1',
            new_name='product',
        ),
    ]
