# Generated by Django 3.2.5 on 2021-07-21 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_auto_20210721_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_img',
            field=models.URLField(blank=True, null=True),
        ),
    ]
