# Generated by Django 3.2.5 on 2021-08-14 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_alter_product_main_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='all_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Вся сума'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='discount',
            field=models.IntegerField(default=0, verbose_name='Сума із знижкою'),
        ),
    ]
