# Generated by Django 3.2.5 on 2021-08-14 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_auto_20210814_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='all_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Вся сума'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Сума із знижкою'),
        ),
    ]
