# Generated by Django 3.2.5 on 2021-09-08 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_reminder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reminder',
            options={'verbose_name': 'Нагадування', 'verbose_name_plural': 'Нагадування'},
        ),
    ]
