# Generated by Django 3.2.5 on 2021-09-20 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_ratingproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RatingProduct',
        ),
    ]
