# Generated by Django 3.2.5 on 2021-09-20 19:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_delete_ratingproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1, message='не менше 1'), django.core.validators.MaxValueValidator(limit_value=5, message='не більше 5')], verbose_name='Значення')),
                ('ip_address_user', models.GenericIPAddressField(verbose_name='IP адрес користувача')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='shop.product')),
            ],
        ),
    ]
