# Generated by Django 3.2.5 on 2021-09-21 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_ratingproduct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratingproduct',
            options={'verbose_name': 'Рейтинг продуктів', 'verbose_name_plural': 'Рейтинг продукту'},
        ),
    ]
