# Generated by Django 3.1.7 on 2021-11-21 12:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_auto_20211121_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingproduct',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(limit_value=1, message='не менше 1'), django.core.validators.MaxValueValidator(limit_value=5, message='не більше 5')], verbose_name='Значення'),
        ),
    ]
