# Generated by Django 3.2.5 on 2021-07-08 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_type_delivery'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_order',
            field=models.ManyToManyField(related_name='orders_customer', to='order.Order', verbose_name='Замовлення покупця'),
        ),
    ]
